config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/:id/account', to:'users#account', as: 'user_account'
  get 'users/:id/profile', to:'users#profile', as: 'user_profile'
  get 'reservations/index'
  post 'reservations/confirm'
  get 'rooms/index'
  root 'top#index'

  resources :rooms do
    get :search, on: :collection
  end
  resources :rooms, only: [:index, :new, :create, :show]
  
  resources :reservations, only: [:index, :new, :create, :show]
  
  resources :users, only: [:update] 
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservation
  mount_uploader :room_image, ImageUploader

  validates :room_name, presence: true
  validates :room_introduction, presence: true
  validates :room_price, presence: true, numericality: true
  validates :room_address, presence: true
  validates :room_image, presence:true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:room_name, :room_introduction, :room_price, :room_address, :room_image, :user_id))
    if @room.save
      flash[:notice] = "Room was successfully created."
      redirect_to @room
    else
      flash[:alert] = "必須項目に入力してください"
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = @room.user
  end

  def search
    @rooms = Room.where('room_address LIKE ?', "%#{params[:room_address]}%").where('room_introduction LIKE ? OR room_name LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
    @numbers = @rooms.count
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="container-field rooms">
  <h4>登録済みルーム一覧</h4>
  <table class="rooms">
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成時</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <% if room.user_id == current_user.id %>
          <tr>
            <td><%= link_to (image_tag room.room_image.url, :size => '240x140'), room_path(room.id) %></td>
            <td class="posts-name"><%= link_to room.room_name, room_path(room.id) %></td>
            <td class="posts-contents"><%= room.room_introduction %></td>
            <td>¥ <%= room.room_price %></td>
            <td><%= room.created_at %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class="row room-nav-menu">
  <div class="room-nav room-nav-pc">
    <ul>
      <li class="active">
        <%= link_to "基本情報", new_room_path %>
      </li>
    </ul>
  </div>
  <div class="room-nav room-nav-mobile">
    <ul>
      <li class="active">
        <%= link_to "基本情報", new_room_path %>
      </li>
    </ul>
  </div>


  <div class="room-view">
    <div class="update-content">
      <div class="room-view-box">
        <div class="row">
          <h5>ルーム情報登録</h5>
        </div>
      </div>
    </div>
    <div class="update-content">
      <%= form_with(model: @room, local: true) do |f| %>
        <table>
          <tr>
            <th><%= f.label :room_name ,"ルーム名", class: "required" %></th>
            <td><%= f.text_field :room_name, class: "input-area" %></td>
          </tr>

          <tr>
            <th><%= f.label :room_introduction ,"ルーム紹介", class: "required" %></th>
            <td><%= f.text_area :room_introduction, class: "input-area" %></td>
          </tr>

          <tr>
            <th><%= f.label :room_price ,"料金", class: "required" %></th>
            <td><%= f.text_field :room_price, class: "input-area" %></td>
          </tr>

          <tr>
          <th><%= f.label :room_address ,"住所", class: "required" %></th>
          <td><%= f.text_area :room_address, class: "input-area" %></td>
          </tr>

          <tr>
            <th><%= f.label :room_image ,"ルーム画像", class: "required" %></th>
            <td><%= f.file_field :room_image, class: "room-image" %></td>
          </tr>

          <tr>
            <%= f.hidden_field :user_id, value: current_user.id %>
          </tr>
        </table>
          
        <div>
          <%= f.submit "登録", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="container-fluid room">
  <h4><%= "検索結果：#{@numbers}件" %></h4>
  <div class="row room-row">
    <div class="room-information">
      <% @rooms.each do |room| %>
        <div class="room-frame-inner">
            <%= link_to controller: 'rooms', action: 'show', id: room.id do %>
                <div class="room-image-out">
                  <%= image_tag room.room_image.url, :alt => 'ルーム画像', class: "frame-room-image" %>
                  <div class="room-profile">
                    <p class="room-profile-name">
                      <%= room.room_name %>
                    </p>
                    <p class="room-profile-city">
                      <%= room.room_address %>
                    </p>
                    <p class="room-profile-price">
                      ¥<%= room.room_price %>
                    </p>
                  </div>
                </div>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="room-show-detail">
      <%= image_tag @room.room_image.url, class: "room-image" %>
      <div class="room-show-detail-content">
        <div class="room-show-detail-icon">
          <%= link_to root_path do %>
            <%= image_tag @room.user.user_image.url, :alt => 'アイコン', class: "host-icon" %>
          <% end %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name">
            <%= @room.room_name %>
          </p>
          <p class="room-show-profile-address">
            <%= @room.room_address %>
          </p>
        </div>
      </div>

      <p class="room-show-detail-introduction">
        <%= @room.room_introduction %>
      </p>
    </div>

    <div class="room-show-nav">
      <h5 class="price-icon">
      ￥ <%= @room.room_price %> / 日
      </h5>
      
      <% if user_signed_in? %> 
        <div class="room-show-date-select">
          <%= form_with url: reservations_confirm_path do |f| %>

            <%= f.hidden_field :room_id, value: @room.id %>

            <%= f.label :reservation_start, "開始日" %>
            <%= f.date_field :reservation_start, class: "input-area" %>

            <%= f.label :reservation_end, "終了日" %>
            <%= f.date_field :reservation_end, class: "input-area" %>

            <%= f.label :reservation_people, "人数" %>
            <%= f.number_field :reservation_people, class: "input-area" %>

            <%= f.submit"予約する", class: "btn room-reservation-submit" %>

          <% end %>
        <% else %>
          <%= form_with url: reservations_confirm_path do |f| %>

            <%= f.hidden_field :room_id, value: @room.id %>

            <%= f.label :reservation_start, "開始日" %>
            <%= f.date_field :reservation_start, class: "input-area" %>

            <%= f.label :reservation_end, "終了日" %>
            <%= f.date_field :reservation_end, class: "input-area" %>

            <%= f.label :reservation_people, "人数" %>
            <%= f.number_field :reservation_people, class: "input-area" %>

            <%= link_to "ログイン", user_session_path, class: "btn room-login-btn" %>
          <% end %>
        <% end %>


      </div>
    </div>

  </div>
</div>